# Generated by Django 5.0 on 2023-12-15 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('pno', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'panel',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rno', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('account', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('limit', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('fno', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('panel', models.ForeignKey(blank=True, db_column='panel_pno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.panel')),
                ('room', models.ForeignKey(blank=True, db_column='room_rno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.room')),
            ],
            options={
                'db_table': 'furniture',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rno', models.BigAutoField(primary_key=True, serialize=False)),
                ('scene', models.CharField(blank=True, max_length=45, null=True)),
                ('panel', models.ForeignKey(blank=True, db_column='panel_pno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.panel')),
                ('user', models.ForeignKey(blank=True, db_column='user_uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.user')),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sno', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('data', models.IntegerField()),
                ('panel', models.ForeignKey(blank=True, db_column='panel_pno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.panel')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture', models.ForeignKey(blank=True, db_column='furniture_fno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.furniture')),
                ('panel', models.ForeignKey(blank=True, db_column='panel_pno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.panel')),
                ('room', models.ForeignKey(blank=True, db_column='room_rno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.room')),
                ('rule', models.OneToOneField(db_column='rule_rno', on_delete=django.db.models.deletion.CASCADE, to='myapp.rule')),
                ('sensor', models.ForeignKey(blank=True, db_column='sensor_sno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.sensor')),
            ],
            options={
                'db_table': 'control',
            },
        ),
    ]
