# Generated by Django 5.0 on 2024-01-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('pno', models.BigAutoField(primary_key=True, serialize=False, verbose_name='pno号')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('fno', models.IntegerField(default=None, verbose_name='编号')),
                ('state', models.SmallIntegerField(choices=[(0, '关'), (1, '开')], default=None, verbose_name='状态')),
            ],
            options={
                'db_table': 'panel',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('rno', models.BigAutoField(primary_key=True, serialize=False, verbose_name='rno号')),
                ('name', models.CharField(max_length=45, verbose_name='房间名')),
                ('num', models.IntegerField(default=0, verbose_name='家具数')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='uid号')),
                ('username', models.CharField(blank=True, max_length=10, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=45, null=True, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name='邮箱')),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('fno', models.BigAutoField(primary_key=True, serialize=False, verbose_name='fno号')),
                ('state', models.SmallIntegerField(choices=[(0, '关'), (1, '开')], default=0, verbose_name='状态')),
                ('name', models.CharField(blank=True, max_length=45, null=True, verbose_name='家具名')),
                ('room', models.ForeignKey(blank=True, db_column='room_rno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.room')),
            ],
            options={
                'db_table': 'furniture',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rno', models.BigAutoField(primary_key=True, serialize=False, verbose_name='rno号')),
                ('scene', models.CharField(blank=True, max_length=45, null=True, verbose_name='场景')),
                ('panel', models.ForeignKey(blank=True, db_column='panel_pno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.panel')),
                ('user', models.ForeignKey(blank=True, db_column='user_uid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.user')),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sno', models.BigAutoField(primary_key=True, serialize=False, verbose_name='sno号')),
                ('name', models.CharField(max_length=45, verbose_name='传感器名')),
                ('data', models.IntegerField(verbose_name='数据')),
                ('panel', models.ForeignKey(blank=True, db_column='panel_pno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.panel')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture', models.ForeignKey(blank=True, db_column='furniture_fno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.furniture')),
                ('panel', models.ForeignKey(blank=True, db_column='panel_pno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.panel')),
                ('room', models.ForeignKey(blank=True, db_column='room_rno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.room')),
                ('rule', models.OneToOneField(db_column='rule_rno', on_delete=django.db.models.deletion.CASCADE, to='myapp.rule', verbose_name='规则')),
                ('sensor', models.ForeignKey(blank=True, db_column='sensor_sno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.sensor')),
            ],
            options={
                'db_table': 'control',
            },
        ),
    ]
