# Generated by Django 5.0 on 2024-01-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='fno',
            field=models.IntegerField(db_column='fno', default=None, verbose_name='编号'),
        ),
    ]
