# Generated by Django 5.0 on 2023-12-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='control',
            name='rule',
            field=models.OneToOneField(db_column='rule_rno', on_delete=django.db.models.deletion.CASCADE, to='myapp.rule', verbose_name='规则'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='fno',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='fno'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='家具名'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='state',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='pno',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='pno'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=45, verbose_name='房间名'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rno',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='rno'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rno',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='rno'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='scene',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='场景'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='data',
            field=models.IntegerField(verbose_name='数据'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=45, verbose_name='传感器名'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sno',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='sno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='uid'),
        ),
    ]
