# Generated by Django 5.0 on 2023-12-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_furniture_fno_alter_panel_pno_alter_room_rno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigAutoField(max_length=10, primary_key=True, serialize=False, verbose_name='uid号'),
        ),
    ]
