# Generated by Django 5.0 on 2023-12-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num',
            field=models.IntegerField(default=0, verbose_name='家具数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='uid号'),
        ),
    ]
